; ============================================================
;  PlatformIO — Arduino Uno Gate Controller
; ============================================================

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600

lib_deps =
    arduino-libraries/Servo@^1.2.2
    bblanchon/ArduinoJson@^7.0.4
